/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UIFrames;

import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Ronaldo
 */
public class Agency_Menu extends javax.swing.JFrame {

    /**
     * Creates new form Logiin_Window
     */
    public Agency_Menu() {
        this.setUndecorated(true);
        
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CreateOffer_InternalFrame = new javax.swing.JInternalFrame();
        ExpireDate_label = new javax.swing.JLabel();
        Day_TextField = new javax.swing.JTextField();
        SelectRoom_Label = new javax.swing.JLabel();
        Discount_TextField = new javax.swing.JTextField();
        Year_TextField = new javax.swing.JTextField();
        Month_TextField = new javax.swing.JTextField();
        Name_TextField = new javax.swing.JTextField();
        YearMonthDay_Label = new javax.swing.JLabel();
        SelectHotel_Label = new javax.swing.JLabel();
        Name_Label = new javax.swing.JLabel();
        Discount_Label = new javax.swing.JLabel();
        SelectRoom_ComboBox = new javax.swing.JComboBox<>();
        SelectHotel_ComboBox = new javax.swing.JComboBox<>();
        Offer_Creation_Button = new javax.swing.JButton();
        External_Frame1 = new javax.swing.JLabel();
        SelectOffer_Change_InternalFrame = new javax.swing.JInternalFrame();
        Existing_Offers_label = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ExistingOffers_Table = new javax.swing.JTable();
        External_Frame3 = new javax.swing.JLabel();
        ChangeOffer_InternalFrame = new javax.swing.JInternalFrame();
        ExpireDate_label1 = new javax.swing.JLabel();
        Day_TextField1 = new javax.swing.JTextField();
        SelectRoom_Label1 = new javax.swing.JLabel();
        Discount_TextField1 = new javax.swing.JTextField();
        Year_TextField1 = new javax.swing.JTextField();
        Month_TextField1 = new javax.swing.JTextField();
        Name_TextField1 = new javax.swing.JTextField();
        YearMonthDay_Label1 = new javax.swing.JLabel();
        SelectHotel_Label1 = new javax.swing.JLabel();
        Name_Label1 = new javax.swing.JLabel();
        Discount_Label1 = new javax.swing.JLabel();
        SelectRoom_ComboBox1 = new javax.swing.JComboBox<>();
        SelectHotel_ComboBox1 = new javax.swing.JComboBox<>();
        Offer_Creation_Button1 = new javax.swing.JButton();
        External_Frame2 = new javax.swing.JLabel();
        DeleteOffer_InternalFrame = new javax.swing.JInternalFrame();
        Existing_Offers_label1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ExistingOffers_Table1 = new javax.swing.JTable();
        External_Frame4 = new javax.swing.JLabel();
        Logo_Label = new javax.swing.JLabel();
        Line_label = new javax.swing.JLabel();
        Agency_Label = new javax.swing.JLabel();
        Exit_Button = new javax.swing.JButton();
        DeleteOffer_Button = new javax.swing.JButton();
        ChangeOffer_Button = new javax.swing.JButton();
        CreateOffer_Button = new javax.swing.JButton();
        Wallpaper_Label = new javax.swing.JLabel();
        External_Frame = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CreateOffer_InternalFrame.setBackground(new java.awt.Color(255, 255, 255));
        CreateOffer_InternalFrame.setBorder(null);
        CreateOffer_InternalFrame.setClosable(true);
        CreateOffer_InternalFrame.setVisible(false);
        CreateOffer_InternalFrame.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ExpireDate_label.setBackground(new java.awt.Color(81, 91, 212));
        ExpireDate_label.setFont(new java.awt.Font("Microsoft YaHei", 1, 18)); // NOI18N
        ExpireDate_label.setForeground(new java.awt.Color(81, 91, 212));
        ExpireDate_label.setText("Expire Date:");
        CreateOffer_InternalFrame.getContentPane().add(ExpireDate_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 120, 30));

        Day_TextField.setBackground(new java.awt.Color(255, 255, 255));
        Day_TextField.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Day_TextField.setForeground(new java.awt.Color(32, 21, 14));
        Day_TextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Day_TextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(81, 91, 212)));
        Day_TextField.setCaretColor(new java.awt.Color(0, 102, 204));
        Day_TextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Day_TextFieldMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Day_TextFieldMouseExited(evt);
            }
        });
        Day_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Day_TextFieldActionPerformed(evt);
            }
        });
        CreateOffer_InternalFrame.getContentPane().add(Day_TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 80, 20));

        SelectRoom_Label.setBackground(new java.awt.Color(81, 91, 212));
        SelectRoom_Label.setFont(new java.awt.Font("Microsoft YaHei", 1, 18)); // NOI18N
        SelectRoom_Label.setForeground(new java.awt.Color(81, 91, 212));
        SelectRoom_Label.setText("Select a Room:");
        CreateOffer_InternalFrame.getContentPane().add(SelectRoom_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 140, 30));

        Discount_TextField.setBackground(new java.awt.Color(255, 255, 255));
        Discount_TextField.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Discount_TextField.setForeground(new java.awt.Color(32, 21, 14));
        Discount_TextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Discount_TextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(81, 91, 212)));
        Discount_TextField.setCaretColor(new java.awt.Color(0, 102, 204));
        Discount_TextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Discount_TextFieldMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Discount_TextFieldMouseExited(evt);
            }
        });
        Discount_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Discount_TextFieldActionPerformed(evt);
            }
        });
        CreateOffer_InternalFrame.getContentPane().add(Discount_TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 130, 20));

        Year_TextField.setBackground(new java.awt.Color(255, 255, 255));
        Year_TextField.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Year_TextField.setForeground(new java.awt.Color(32, 21, 14));
        Year_TextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Year_TextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(81, 91, 212)));
        Year_TextField.setCaretColor(new java.awt.Color(0, 102, 204));
        Year_TextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Year_TextFieldMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Year_TextFieldMouseExited(evt);
            }
        });
        Year_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Year_TextFieldActionPerformed(evt);
            }
        });
        CreateOffer_InternalFrame.getContentPane().add(Year_TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 80, 20));

        Month_TextField.setBackground(new java.awt.Color(255, 255, 255));
        Month_TextField.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Month_TextField.setForeground(new java.awt.Color(32, 21, 14));
        Month_TextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Month_TextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(81, 91, 212)));
        Month_TextField.setCaretColor(new java.awt.Color(0, 102, 204));
        Month_TextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Month_TextFieldMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Month_TextFieldMouseExited(evt);
            }
        });
        Month_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Month_TextFieldActionPerformed(evt);
            }
        });
        CreateOffer_InternalFrame.getContentPane().add(Month_TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 80, 20));

        Name_TextField.setBackground(new java.awt.Color(255, 255, 255));
        Name_TextField.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Name_TextField.setForeground(new java.awt.Color(32, 21, 14));
        Name_TextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Name_TextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(81, 91, 212)));
        Name_TextField.setCaretColor(new java.awt.Color(0, 102, 204));
        Name_TextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Name_TextFieldMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Name_TextFieldMouseExited(evt);
            }
        });
        Name_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Name_TextFieldActionPerformed(evt);
            }
        });
        CreateOffer_InternalFrame.getContentPane().add(Name_TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 340, 20));

        YearMonthDay_Label.setBackground(new java.awt.Color(153, 153, 153));
        YearMonthDay_Label.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        YearMonthDay_Label.setForeground(new java.awt.Color(81, 91, 212));
        YearMonthDay_Label.setText("yyyy       -      mm        -     dd");
        CreateOffer_InternalFrame.getContentPane().add(YearMonthDay_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 250, 30));

        SelectHotel_Label.setBackground(new java.awt.Color(81, 91, 212));
        SelectHotel_Label.setFont(new java.awt.Font("Microsoft YaHei", 1, 18)); // NOI18N
        SelectHotel_Label.setForeground(new java.awt.Color(81, 91, 212));
        SelectHotel_Label.setText("Select an Hotel:");
        CreateOffer_InternalFrame.getContentPane().add(SelectHotel_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 140, 30));

        Name_Label.setBackground(new java.awt.Color(81, 91, 212));
        Name_Label.setFont(new java.awt.Font("Microsoft YaHei", 1, 18)); // NOI18N
        Name_Label.setForeground(new java.awt.Color(81, 91, 212));
        Name_Label.setText("Name:");
        CreateOffer_InternalFrame.getContentPane().add(Name_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 90, 30));

        Discount_Label.setBackground(new java.awt.Color(81, 91, 212));
        Discount_Label.setFont(new java.awt.Font("Microsoft YaHei", 1, 18)); // NOI18N
        Discount_Label.setForeground(new java.awt.Color(81, 91, 212));
        Discount_Label.setText("Discount:");
        CreateOffer_InternalFrame.getContentPane().add(Discount_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 140, 30));

        SelectRoom_ComboBox.setBackground(new java.awt.Color(255, 255, 255));
        SelectRoom_ComboBox.setForeground(new java.awt.Color(32, 21, 14));
        SelectRoom_ComboBox.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(81, 91, 212)));
        SelectRoom_ComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectRoom_ComboBoxActionPerformed(evt);
            }
        });
        CreateOffer_InternalFrame.getContentPane().add(SelectRoom_ComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 270, -1));

        SelectHotel_ComboBox.setBackground(new java.awt.Color(255, 255, 255));
        SelectHotel_ComboBox.setForeground(new java.awt.Color(32, 21, 14));
        SelectHotel_ComboBox.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(81, 91, 212)));
        SelectHotel_ComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectHotel_ComboBoxActionPerformed(evt);
            }
        });
        CreateOffer_InternalFrame.getContentPane().add(SelectHotel_ComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 270, -1));

        Offer_Creation_Button.setFont(new java.awt.Font("Microsoft YaHei", 1, 18)); // NOI18N
        Offer_Creation_Button.setForeground(new java.awt.Color(81, 91, 212));
        Offer_Creation_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Create_Icon.png"))); // NOI18N
        Offer_Creation_Button.setText("Create Offer !");
        Offer_Creation_Button.setBorderPainted(false);
        Offer_Creation_Button.setContentAreaFilled(false);
        Offer_Creation_Button.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        Offer_Creation_Button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Offer_Creation_Button.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        CreateOffer_InternalFrame.getContentPane().add(Offer_Creation_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 440, 160, 100));

        External_Frame1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/White_Wallpaper.jpg"))); // NOI18N
        CreateOffer_InternalFrame.getContentPane().add(External_Frame1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 570));

        getContentPane().add(CreateOffer_InternalFrame, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 120, 650, 590));

        SelectOffer_Change_InternalFrame.setBackground(new java.awt.Color(255, 255, 255));
        SelectOffer_Change_InternalFrame.setBorder(null);
        SelectOffer_Change_InternalFrame.setClosable(true);
        SelectOffer_Change_InternalFrame.setVisible(false);
        SelectOffer_Change_InternalFrame.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Existing_Offers_label.setBackground(new java.awt.Color(81, 91, 212));
        Existing_Offers_label.setFont(new java.awt.Font("Microsoft YaHei", 1, 24)); // NOI18N
        Existing_Offers_label.setForeground(new java.awt.Color(245, 133, 41));
        Existing_Offers_label.setText("Existing Offers:");
        SelectOffer_Change_InternalFrame.getContentPane().add(Existing_Offers_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, 200, 30));

        ExistingOffers_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(ExistingOffers_Table);

        SelectOffer_Change_InternalFrame.getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 610, 450));

        External_Frame3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/White_Wallpaper.jpg"))); // NOI18N
        SelectOffer_Change_InternalFrame.getContentPane().add(External_Frame3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 570));

        getContentPane().add(SelectOffer_Change_InternalFrame, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 120, 650, 590));

        ChangeOffer_InternalFrame.setBackground(new java.awt.Color(255, 255, 255));
        ChangeOffer_InternalFrame.setBorder(null);
        ChangeOffer_InternalFrame.setClosable(true);
        ChangeOffer_InternalFrame.setVisible(false);
        ChangeOffer_InternalFrame.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ExpireDate_label1.setBackground(new java.awt.Color(81, 91, 212));
        ExpireDate_label1.setFont(new java.awt.Font("Microsoft YaHei", 1, 18)); // NOI18N
        ExpireDate_label1.setForeground(new java.awt.Color(245, 133, 41));
        ExpireDate_label1.setText("Expire Date:");
        ChangeOffer_InternalFrame.getContentPane().add(ExpireDate_label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 120, 30));

        Day_TextField1.setBackground(new java.awt.Color(255, 255, 255));
        Day_TextField1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Day_TextField1.setForeground(new java.awt.Color(32, 21, 14));
        Day_TextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Day_TextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(245, 133, 41)));
        Day_TextField1.setCaretColor(new java.awt.Color(0, 102, 204));
        Day_TextField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Day_TextField1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Day_TextField1MouseExited(evt);
            }
        });
        Day_TextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Day_TextField1ActionPerformed(evt);
            }
        });
        ChangeOffer_InternalFrame.getContentPane().add(Day_TextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 80, 20));

        SelectRoom_Label1.setBackground(new java.awt.Color(81, 91, 212));
        SelectRoom_Label1.setFont(new java.awt.Font("Microsoft YaHei", 1, 18)); // NOI18N
        SelectRoom_Label1.setForeground(new java.awt.Color(245, 133, 41));
        SelectRoom_Label1.setText("Select a Room:");
        ChangeOffer_InternalFrame.getContentPane().add(SelectRoom_Label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 140, 30));

        Discount_TextField1.setBackground(new java.awt.Color(255, 255, 255));
        Discount_TextField1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Discount_TextField1.setForeground(new java.awt.Color(32, 21, 14));
        Discount_TextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Discount_TextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(245, 133, 41)));
        Discount_TextField1.setCaretColor(new java.awt.Color(0, 102, 204));
        Discount_TextField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Discount_TextField1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Discount_TextField1MouseExited(evt);
            }
        });
        Discount_TextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Discount_TextField1ActionPerformed(evt);
            }
        });
        ChangeOffer_InternalFrame.getContentPane().add(Discount_TextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 130, 20));

        Year_TextField1.setBackground(new java.awt.Color(255, 255, 255));
        Year_TextField1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Year_TextField1.setForeground(new java.awt.Color(32, 21, 14));
        Year_TextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Year_TextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(245, 133, 41)));
        Year_TextField1.setCaretColor(new java.awt.Color(0, 102, 204));
        Year_TextField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Year_TextField1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Year_TextField1MouseExited(evt);
            }
        });
        Year_TextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Year_TextField1ActionPerformed(evt);
            }
        });
        ChangeOffer_InternalFrame.getContentPane().add(Year_TextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 80, 20));

        Month_TextField1.setBackground(new java.awt.Color(255, 255, 255));
        Month_TextField1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Month_TextField1.setForeground(new java.awt.Color(32, 21, 14));
        Month_TextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Month_TextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(245, 133, 41)));
        Month_TextField1.setCaretColor(new java.awt.Color(0, 102, 204));
        Month_TextField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Month_TextField1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Month_TextField1MouseExited(evt);
            }
        });
        Month_TextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Month_TextField1ActionPerformed(evt);
            }
        });
        ChangeOffer_InternalFrame.getContentPane().add(Month_TextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 80, 20));

        Name_TextField1.setBackground(new java.awt.Color(255, 255, 255));
        Name_TextField1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Name_TextField1.setForeground(new java.awt.Color(32, 21, 14));
        Name_TextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Name_TextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(245, 133, 41)));
        Name_TextField1.setCaretColor(new java.awt.Color(0, 102, 204));
        Name_TextField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Name_TextField1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Name_TextField1MouseExited(evt);
            }
        });
        Name_TextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Name_TextField1ActionPerformed(evt);
            }
        });
        ChangeOffer_InternalFrame.getContentPane().add(Name_TextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 340, 20));

        YearMonthDay_Label1.setBackground(new java.awt.Color(153, 153, 153));
        YearMonthDay_Label1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        YearMonthDay_Label1.setForeground(new java.awt.Color(245, 133, 41));
        YearMonthDay_Label1.setText("yyyy       -      mm        -     dd");
        ChangeOffer_InternalFrame.getContentPane().add(YearMonthDay_Label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 250, 30));

        SelectHotel_Label1.setBackground(new java.awt.Color(81, 91, 212));
        SelectHotel_Label1.setFont(new java.awt.Font("Microsoft YaHei", 1, 18)); // NOI18N
        SelectHotel_Label1.setForeground(new java.awt.Color(245, 133, 41));
        SelectHotel_Label1.setText("Select an Hotel:");
        ChangeOffer_InternalFrame.getContentPane().add(SelectHotel_Label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 140, 30));

        Name_Label1.setBackground(new java.awt.Color(81, 91, 212));
        Name_Label1.setFont(new java.awt.Font("Microsoft YaHei", 1, 18)); // NOI18N
        Name_Label1.setForeground(new java.awt.Color(245, 133, 41));
        Name_Label1.setText("Name:");
        ChangeOffer_InternalFrame.getContentPane().add(Name_Label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 90, 30));

        Discount_Label1.setBackground(new java.awt.Color(81, 91, 212));
        Discount_Label1.setFont(new java.awt.Font("Microsoft YaHei", 1, 18)); // NOI18N
        Discount_Label1.setForeground(new java.awt.Color(245, 133, 41));
        Discount_Label1.setText("Discount:");
        ChangeOffer_InternalFrame.getContentPane().add(Discount_Label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 140, 30));

        SelectRoom_ComboBox1.setBackground(new java.awt.Color(255, 255, 255));
        SelectRoom_ComboBox1.setForeground(new java.awt.Color(32, 21, 14));
        SelectRoom_ComboBox1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(245, 133, 41)));
        SelectRoom_ComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectRoom_ComboBox1ActionPerformed(evt);
            }
        });
        ChangeOffer_InternalFrame.getContentPane().add(SelectRoom_ComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 270, -1));

        SelectHotel_ComboBox1.setBackground(new java.awt.Color(255, 255, 255));
        SelectHotel_ComboBox1.setForeground(new java.awt.Color(51, 51, 51));
        SelectHotel_ComboBox1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(245, 133, 41)));
        SelectHotel_ComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectHotel_ComboBox1ActionPerformed(evt);
            }
        });
        ChangeOffer_InternalFrame.getContentPane().add(SelectHotel_ComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 270, -1));

        Offer_Creation_Button1.setFont(new java.awt.Font("Microsoft YaHei", 1, 18)); // NOI18N
        Offer_Creation_Button1.setForeground(new java.awt.Color(245, 133, 41));
        Offer_Creation_Button1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Change_icon (2).png"))); // NOI18N
        Offer_Creation_Button1.setText("Change Offer Info!");
        Offer_Creation_Button1.setBorderPainted(false);
        Offer_Creation_Button1.setContentAreaFilled(false);
        Offer_Creation_Button1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        Offer_Creation_Button1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Offer_Creation_Button1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ChangeOffer_InternalFrame.getContentPane().add(Offer_Creation_Button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 440, 210, 100));

        External_Frame2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/White_Wallpaper.jpg"))); // NOI18N
        ChangeOffer_InternalFrame.getContentPane().add(External_Frame2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 570));

        getContentPane().add(ChangeOffer_InternalFrame, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 120, 650, 590));

        DeleteOffer_InternalFrame.setBackground(new java.awt.Color(255, 255, 255));
        DeleteOffer_InternalFrame.setBorder(null);
        DeleteOffer_InternalFrame.setClosable(true);
        DeleteOffer_InternalFrame.setVisible(false);
        DeleteOffer_InternalFrame.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Existing_Offers_label1.setBackground(new java.awt.Color(81, 91, 212));
        Existing_Offers_label1.setFont(new java.awt.Font("Microsoft YaHei", 1, 24)); // NOI18N
        Existing_Offers_label1.setForeground(new java.awt.Color(236, 72, 76));
        Existing_Offers_label1.setText("Existing Offers:");
        DeleteOffer_InternalFrame.getContentPane().add(Existing_Offers_label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, 200, 30));

        ExistingOffers_Table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(ExistingOffers_Table1);

        DeleteOffer_InternalFrame.getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 610, 450));

        External_Frame4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/White_Wallpaper.jpg"))); // NOI18N
        DeleteOffer_InternalFrame.getContentPane().add(External_Frame4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 570));

        getContentPane().add(DeleteOffer_InternalFrame, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 120, 650, 590));

        Logo_Label.setFont(new java.awt.Font("Microsoft YaHei", 1, 36)); // NOI18N
        Logo_Label.setForeground(new java.awt.Color(129, 52, 175));
        Logo_Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Mini_Logo2.png"))); // NOI18N
        Logo_Label.setText("My Travel Home ");
        Logo_Label.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        getContentPane().add(Logo_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 10, 400, 70));

        Line_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/line.PNG"))); // NOI18N
        Line_label.setText("jLabel3");
        getContentPane().add(Line_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 80, 10, 630));

        Agency_Label.setBackground(new java.awt.Color(81, 91, 212));
        Agency_Label.setFont(new java.awt.Font("Microsoft YaHei", 1, 20)); // NOI18N
        Agency_Label.setForeground(new java.awt.Color(57, 23, 77));
        Agency_Label.setText("Agency Management");
        getContentPane().add(Agency_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 80, 220, 30));

        Exit_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Exit Button.png"))); // NOI18N
        Exit_Button.setToolTipText("");
        Exit_Button.setBorder(null);
        Exit_Button.setContentAreaFilled(false);
        Exit_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Exit_ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(Exit_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 10, 30, 30));

        DeleteOffer_Button.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        DeleteOffer_Button.setForeground(new java.awt.Color(236, 72, 76));
        DeleteOffer_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Delete_Icon.png"))); // NOI18N
        DeleteOffer_Button.setText("Delete an Offer");
        DeleteOffer_Button.setBorderPainted(false);
        DeleteOffer_Button.setContentAreaFilled(false);
        DeleteOffer_Button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        DeleteOffer_Button.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        DeleteOffer_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteOffer_ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(DeleteOffer_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 480, 150, 150));

        ChangeOffer_Button.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        ChangeOffer_Button.setForeground(new java.awt.Color(245, 133, 41));
        ChangeOffer_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Change_Icon.png"))); // NOI18N
        ChangeOffer_Button.setText("Change Offer Information");
        ChangeOffer_Button.setBorderPainted(false);
        ChangeOffer_Button.setContentAreaFilled(false);
        ChangeOffer_Button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ChangeOffer_Button.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ChangeOffer_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChangeOffer_ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ChangeOffer_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 230, 220, -1));

        CreateOffer_Button.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        CreateOffer_Button.setForeground(new java.awt.Color(81, 91, 212));
        CreateOffer_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Offer_Icon.png"))); // NOI18N
        CreateOffer_Button.setText("Create a New Offer");
        CreateOffer_Button.setBorderPainted(false);
        CreateOffer_Button.setContentAreaFilled(false);
        CreateOffer_Button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        CreateOffer_Button.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        CreateOffer_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateOffer_ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(CreateOffer_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 230, -1, -1));

        Wallpaper_Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Forest_Hotel_Photo2.jpg"))); // NOI18N
        Wallpaper_Label.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        getContentPane().add(Wallpaper_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 570, 700));

        External_Frame.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/White_Wallpaper.jpg"))); // NOI18N
        getContentPane().add(External_Frame, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Exit_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Exit_ButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_Exit_ButtonActionPerformed

    private void CreateOffer_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateOffer_ButtonActionPerformed

        CreateOffer_InternalFrame.setVisible(true);
        
    }//GEN-LAST:event_CreateOffer_ButtonActionPerformed

    private void Day_TextFieldMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Day_TextFieldMouseEntered
        Day_TextField.setBackground(new java.awt.Color(216,216,216));
    }//GEN-LAST:event_Day_TextFieldMouseEntered

    private void Day_TextFieldMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Day_TextFieldMouseExited
        Day_TextField.setBackground(new java.awt.Color(255,255,255));
    }//GEN-LAST:event_Day_TextFieldMouseExited

    private void Day_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Day_TextFieldActionPerformed
        Day_TextField.setText("");
    }//GEN-LAST:event_Day_TextFieldActionPerformed

    private void Discount_TextFieldMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Discount_TextFieldMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_Discount_TextFieldMouseEntered

    private void Discount_TextFieldMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Discount_TextFieldMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_Discount_TextFieldMouseExited

    private void Discount_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Discount_TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Discount_TextFieldActionPerformed

    private void Year_TextFieldMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Year_TextFieldMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_Year_TextFieldMouseEntered

    private void Year_TextFieldMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Year_TextFieldMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_Year_TextFieldMouseExited

    private void Year_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Year_TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Year_TextFieldActionPerformed

    private void Month_TextFieldMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Month_TextFieldMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_Month_TextFieldMouseEntered

    private void Month_TextFieldMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Month_TextFieldMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_Month_TextFieldMouseExited

    private void Month_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Month_TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Month_TextFieldActionPerformed

    private void SelectRoom_ComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectRoom_ComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SelectRoom_ComboBoxActionPerformed

    private void SelectHotel_ComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectHotel_ComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SelectHotel_ComboBoxActionPerformed

    private void Name_TextFieldMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Name_TextFieldMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_Name_TextFieldMouseEntered

    private void Name_TextFieldMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Name_TextFieldMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_Name_TextFieldMouseExited

    private void Name_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Name_TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Name_TextFieldActionPerformed

    private void Day_TextField1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Day_TextField1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_Day_TextField1MouseEntered

    private void Day_TextField1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Day_TextField1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_Day_TextField1MouseExited

    private void Day_TextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Day_TextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Day_TextField1ActionPerformed

    private void Discount_TextField1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Discount_TextField1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_Discount_TextField1MouseEntered

    private void Discount_TextField1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Discount_TextField1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_Discount_TextField1MouseExited

    private void Discount_TextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Discount_TextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Discount_TextField1ActionPerformed

    private void Year_TextField1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Year_TextField1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_Year_TextField1MouseEntered

    private void Year_TextField1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Year_TextField1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_Year_TextField1MouseExited

    private void Year_TextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Year_TextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Year_TextField1ActionPerformed

    private void Month_TextField1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Month_TextField1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_Month_TextField1MouseEntered

    private void Month_TextField1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Month_TextField1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_Month_TextField1MouseExited

    private void Month_TextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Month_TextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Month_TextField1ActionPerformed

    private void Name_TextField1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Name_TextField1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_Name_TextField1MouseEntered

    private void Name_TextField1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Name_TextField1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_Name_TextField1MouseExited

    private void Name_TextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Name_TextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Name_TextField1ActionPerformed

    private void SelectRoom_ComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectRoom_ComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SelectRoom_ComboBox1ActionPerformed

    private void SelectHotel_ComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectHotel_ComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SelectHotel_ComboBox1ActionPerformed

    private void ChangeOffer_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChangeOffer_ButtonActionPerformed
        SelectOffer_Change_InternalFrame.setVisible(true);
    }//GEN-LAST:event_ChangeOffer_ButtonActionPerformed

    private void DeleteOffer_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteOffer_ButtonActionPerformed
        DeleteOffer_InternalFrame.setVisible(true);
    }//GEN-LAST:event_DeleteOffer_ButtonActionPerformed

    /**
     * @param args the command line arguments
    */

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Agency_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Agency_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Agency_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Agency_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Agency_Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Agency_Label;
    private javax.swing.JButton ChangeOffer_Button;
    private javax.swing.JInternalFrame ChangeOffer_InternalFrame;
    private javax.swing.JButton CreateOffer_Button;
    private javax.swing.JInternalFrame CreateOffer_InternalFrame;
    private javax.swing.JTextField Day_TextField;
    private javax.swing.JTextField Day_TextField1;
    private javax.swing.JButton DeleteOffer_Button;
    private javax.swing.JInternalFrame DeleteOffer_InternalFrame;
    private javax.swing.JLabel Discount_Label;
    private javax.swing.JLabel Discount_Label1;
    private javax.swing.JTextField Discount_TextField;
    private javax.swing.JTextField Discount_TextField1;
    private javax.swing.JTable ExistingOffers_Table;
    private javax.swing.JTable ExistingOffers_Table1;
    private javax.swing.JLabel Existing_Offers_label;
    private javax.swing.JLabel Existing_Offers_label1;
    private javax.swing.JButton Exit_Button;
    private javax.swing.JLabel ExpireDate_label;
    private javax.swing.JLabel ExpireDate_label1;
    private javax.swing.JLabel External_Frame;
    private javax.swing.JLabel External_Frame1;
    private javax.swing.JLabel External_Frame2;
    private javax.swing.JLabel External_Frame3;
    private javax.swing.JLabel External_Frame4;
    private javax.swing.JLabel Line_label;
    private javax.swing.JLabel Logo_Label;
    private javax.swing.JTextField Month_TextField;
    private javax.swing.JTextField Month_TextField1;
    private javax.swing.JLabel Name_Label;
    private javax.swing.JLabel Name_Label1;
    private javax.swing.JTextField Name_TextField;
    private javax.swing.JTextField Name_TextField1;
    private javax.swing.JButton Offer_Creation_Button;
    private javax.swing.JButton Offer_Creation_Button1;
    private javax.swing.JComboBox<String> SelectHotel_ComboBox;
    private javax.swing.JComboBox<String> SelectHotel_ComboBox1;
    private javax.swing.JLabel SelectHotel_Label;
    private javax.swing.JLabel SelectHotel_Label1;
    private javax.swing.JInternalFrame SelectOffer_Change_InternalFrame;
    private javax.swing.JComboBox<String> SelectRoom_ComboBox;
    private javax.swing.JComboBox<String> SelectRoom_ComboBox1;
    private javax.swing.JLabel SelectRoom_Label;
    private javax.swing.JLabel SelectRoom_Label1;
    private javax.swing.JLabel Wallpaper_Label;
    private javax.swing.JLabel YearMonthDay_Label;
    private javax.swing.JLabel YearMonthDay_Label1;
    private javax.swing.JTextField Year_TextField;
    private javax.swing.JTextField Year_TextField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
