/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UIFrames;

import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Ronaldo
 */
public class Hotel_Menu extends javax.swing.JFrame {

    /**
     * Creates new form Logiin_Window
     */
    public Hotel_Menu() {
        this.setUndecorated(true);
        
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CreateHotel_InternalFrame = new javax.swing.JInternalFrame();
        Photo_Button = new javax.swing.JButton();
        SelectDistrict_Label = new javax.swing.JLabel();
        SelectCanton_Label = new javax.swing.JLabel();
        SelectHotelCategory_Label = new javax.swing.JLabel();
        SelectProvince_Label = new javax.swing.JLabel();
        SelectLocation_Label = new javax.swing.JLabel();
        Name_TextField = new javax.swing.JTextField();
        SelectHotelCategory_ComboBox = new javax.swing.JComboBox<>();
        SelectProvince_ComboBox = new javax.swing.JComboBox<>();
        SelectCatnton_ComboBox = new javax.swing.JComboBox<>();
        SelectHotelStars_Label = new javax.swing.JLabel();
        SelectCountry_Label = new javax.swing.JLabel();
        Name_Label = new javax.swing.JLabel();
        SelectCountry_ComboBox = new javax.swing.JComboBox<>();
        SelectHotelStars_ComboBox = new javax.swing.JComboBox<>();
        Offer_Creation_Button = new javax.swing.JButton();
        Photo_Label = new javax.swing.JLabel();
        SelectDistrict_ComboBox = new javax.swing.JComboBox<>();
        External_Frame1 = new javax.swing.JLabel();
        CreateRooms_InterlnalFrame = new javax.swing.JInternalFrame();
        Existing_Offers_label = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ExistingOffers_Table = new javax.swing.JTable();
        External_Frame3 = new javax.swing.JLabel();
        ChangeOffer_InternalFrame = new javax.swing.JInternalFrame();
        ExpireDate_label1 = new javax.swing.JLabel();
        Day_TextField1 = new javax.swing.JTextField();
        SelectRoom_Label1 = new javax.swing.JLabel();
        Discount_TextField1 = new javax.swing.JTextField();
        Year_TextField1 = new javax.swing.JTextField();
        Month_TextField1 = new javax.swing.JTextField();
        Name_TextField1 = new javax.swing.JTextField();
        YearMonthDay_Label1 = new javax.swing.JLabel();
        SelectHotel_Label1 = new javax.swing.JLabel();
        Name_Label1 = new javax.swing.JLabel();
        Discount_Label1 = new javax.swing.JLabel();
        SelectRoom_ComboBox1 = new javax.swing.JComboBox<>();
        SelectHotel_ComboBox1 = new javax.swing.JComboBox<>();
        Offer_Creation_Button1 = new javax.swing.JButton();
        External_Frame2 = new javax.swing.JLabel();
        DeleteOffer_InternalFrame = new javax.swing.JInternalFrame();
        Existing_Offers_label1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ExistingOffers_Table1 = new javax.swing.JTable();
        External_Frame4 = new javax.swing.JLabel();
        Logo_Label = new javax.swing.JLabel();
        Line_label = new javax.swing.JLabel();
        Agency_Label = new javax.swing.JLabel();
        Exit_Button = new javax.swing.JButton();
        DeleteOffer_Button = new javax.swing.JButton();
        ChangeOffer_Button = new javax.swing.JButton();
        CreateHotel_Button = new javax.swing.JButton();
        CreateHotel_Button1 = new javax.swing.JButton();
        CreateHotel_Button2 = new javax.swing.JButton();
        Wallpaper_Label = new javax.swing.JLabel();
        External_Frame = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CreateHotel_InternalFrame.setBackground(new java.awt.Color(255, 255, 255));
        CreateHotel_InternalFrame.setBorder(null);
        CreateHotel_InternalFrame.setClosable(true);
        CreateHotel_InternalFrame.setVisible(false);
        CreateHotel_InternalFrame.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Photo_Button.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        Photo_Button.setForeground(new java.awt.Color(153, 153, 153));
        Photo_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/photo.png"))); // NOI18N
        Photo_Button.setBorderPainted(false);
        Photo_Button.setContentAreaFilled(false);
        Photo_Button.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        Photo_Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Photo_ButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Photo_ButtonMouseExited(evt);
            }
        });
        Photo_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Photo_ButtonActionPerformed(evt);
            }
        });
        CreateHotel_InternalFrame.getContentPane().add(Photo_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 180, 80, 100));

        SelectDistrict_Label.setBackground(new java.awt.Color(81, 91, 212));
        SelectDistrict_Label.setFont(new java.awt.Font("Microsoft YaHei", 1, 18)); // NOI18N
        SelectDistrict_Label.setForeground(new java.awt.Color(81, 91, 212));
        SelectDistrict_Label.setText("Select a District:");
        CreateHotel_InternalFrame.getContentPane().add(SelectDistrict_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, 170, 30));

        SelectCanton_Label.setBackground(new java.awt.Color(81, 91, 212));
        SelectCanton_Label.setFont(new java.awt.Font("Microsoft YaHei", 1, 18)); // NOI18N
        SelectCanton_Label.setForeground(new java.awt.Color(81, 91, 212));
        SelectCanton_Label.setText("Select a Canton:");
        CreateHotel_InternalFrame.getContentPane().add(SelectCanton_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 170, 30));

        SelectHotelCategory_Label.setBackground(new java.awt.Color(81, 91, 212));
        SelectHotelCategory_Label.setFont(new java.awt.Font("Microsoft YaHei", 1, 18)); // NOI18N
        SelectHotelCategory_Label.setForeground(new java.awt.Color(81, 91, 212));
        SelectHotelCategory_Label.setText("Select Hotel Category:");
        CreateHotel_InternalFrame.getContentPane().add(SelectHotelCategory_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 210, 30));

        SelectProvince_Label.setBackground(new java.awt.Color(81, 91, 212));
        SelectProvince_Label.setFont(new java.awt.Font("Microsoft YaHei", 1, 18)); // NOI18N
        SelectProvince_Label.setForeground(new java.awt.Color(81, 91, 212));
        SelectProvince_Label.setText("Select a Province:");
        CreateHotel_InternalFrame.getContentPane().add(SelectProvince_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 170, 30));

        SelectLocation_Label.setBackground(new java.awt.Color(81, 91, 212));
        SelectLocation_Label.setFont(new java.awt.Font("Microsoft YaHei", 1, 18)); // NOI18N
        SelectLocation_Label.setForeground(new java.awt.Color(81, 91, 212));
        SelectLocation_Label.setText("Select a Location:");
        CreateHotel_InternalFrame.getContentPane().add(SelectLocation_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 170, 30));

        Name_TextField.setBackground(new java.awt.Color(255, 255, 255));
        Name_TextField.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Name_TextField.setForeground(new java.awt.Color(32, 21, 14));
        Name_TextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Name_TextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(81, 91, 212)));
        Name_TextField.setCaretColor(new java.awt.Color(0, 102, 204));
        Name_TextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Name_TextFieldMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Name_TextFieldMouseExited(evt);
            }
        });
        Name_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Name_TextFieldActionPerformed(evt);
            }
        });
        CreateHotel_InternalFrame.getContentPane().add(Name_TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 340, 20));

        SelectHotelCategory_ComboBox.setBackground(new java.awt.Color(255, 255, 255));
        SelectHotelCategory_ComboBox.setForeground(new java.awt.Color(32, 21, 14));
        SelectHotelCategory_ComboBox.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(81, 91, 212)));
        SelectHotelCategory_ComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectHotelCategory_ComboBoxActionPerformed(evt);
            }
        });
        CreateHotel_InternalFrame.getContentPane().add(SelectHotelCategory_ComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 270, -1));

        SelectProvince_ComboBox.setBackground(new java.awt.Color(255, 255, 255));
        SelectProvince_ComboBox.setForeground(new java.awt.Color(32, 21, 14));
        SelectProvince_ComboBox.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(81, 91, 212)));
        SelectProvince_ComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectProvince_ComboBoxActionPerformed(evt);
            }
        });
        CreateHotel_InternalFrame.getContentPane().add(SelectProvince_ComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, 270, -1));

        SelectCatnton_ComboBox.setBackground(new java.awt.Color(255, 255, 255));
        SelectCatnton_ComboBox.setForeground(new java.awt.Color(32, 21, 14));
        SelectCatnton_ComboBox.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(81, 91, 212)));
        SelectCatnton_ComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectCatnton_ComboBoxActionPerformed(evt);
            }
        });
        CreateHotel_InternalFrame.getContentPane().add(SelectCatnton_ComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 470, 270, -1));

        SelectHotelStars_Label.setBackground(new java.awt.Color(81, 91, 212));
        SelectHotelStars_Label.setFont(new java.awt.Font("Microsoft YaHei", 1, 18)); // NOI18N
        SelectHotelStars_Label.setForeground(new java.awt.Color(81, 91, 212));
        SelectHotelStars_Label.setText("Select Hotel Stars:");
        CreateHotel_InternalFrame.getContentPane().add(SelectHotelStars_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 170, 30));

        SelectCountry_Label.setBackground(new java.awt.Color(81, 91, 212));
        SelectCountry_Label.setFont(new java.awt.Font("Microsoft YaHei", 1, 18)); // NOI18N
        SelectCountry_Label.setForeground(new java.awt.Color(81, 91, 212));
        SelectCountry_Label.setText("Select a Country:");
        CreateHotel_InternalFrame.getContentPane().add(SelectCountry_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 170, 30));

        Name_Label.setBackground(new java.awt.Color(81, 91, 212));
        Name_Label.setFont(new java.awt.Font("Microsoft YaHei", 1, 18)); // NOI18N
        Name_Label.setForeground(new java.awt.Color(81, 91, 212));
        Name_Label.setText("Name:");
        CreateHotel_InternalFrame.getContentPane().add(Name_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 90, 30));

        SelectCountry_ComboBox.setBackground(new java.awt.Color(255, 255, 255));
        SelectCountry_ComboBox.setForeground(new java.awt.Color(32, 21, 14));
        SelectCountry_ComboBox.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(81, 91, 212)));
        SelectCountry_ComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectCountry_ComboBoxActionPerformed(evt);
            }
        });
        CreateHotel_InternalFrame.getContentPane().add(SelectCountry_ComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 270, -1));

        SelectHotelStars_ComboBox.setBackground(new java.awt.Color(255, 255, 255));
        SelectHotelStars_ComboBox.setForeground(new java.awt.Color(32, 21, 14));
        SelectHotelStars_ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));
        SelectHotelStars_ComboBox.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(81, 91, 212)));
        SelectHotelStars_ComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectHotelStars_ComboBoxActionPerformed(evt);
            }
        });
        CreateHotel_InternalFrame.getContentPane().add(SelectHotelStars_ComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 270, -1));

        Offer_Creation_Button.setFont(new java.awt.Font("Microsoft YaHei", 1, 18)); // NOI18N
        Offer_Creation_Button.setForeground(new java.awt.Color(81, 91, 212));
        Offer_Creation_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Create_Icon.png"))); // NOI18N
        Offer_Creation_Button.setText("Create Hotel !");
        Offer_Creation_Button.setBorderPainted(false);
        Offer_Creation_Button.setContentAreaFilled(false);
        Offer_Creation_Button.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        Offer_Creation_Button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Offer_Creation_Button.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        CreateHotel_InternalFrame.getContentPane().add(Offer_Creation_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 450, 160, 100));

        Photo_Label.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Photo_Label.setForeground(new java.awt.Color(129, 52, 175));
        Photo_Label.setText(" Add a Photo");
        CreateHotel_InternalFrame.getContentPane().add(Photo_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 290, 120, 30));

        SelectDistrict_ComboBox.setBackground(new java.awt.Color(255, 255, 255));
        SelectDistrict_ComboBox.setForeground(new java.awt.Color(32, 21, 14));
        SelectDistrict_ComboBox.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(81, 91, 212)));
        SelectDistrict_ComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectDistrict_ComboBoxActionPerformed(evt);
            }
        });
        CreateHotel_InternalFrame.getContentPane().add(SelectDistrict_ComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 530, 270, -1));

        External_Frame1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/White_Wallpaper.jpg"))); // NOI18N
        CreateHotel_InternalFrame.getContentPane().add(External_Frame1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 570));

        getContentPane().add(CreateHotel_InternalFrame, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 120, 650, 590));

        CreateRooms_InterlnalFrame.setBackground(new java.awt.Color(255, 255, 255));
        CreateRooms_InterlnalFrame.setBorder(null);
        CreateRooms_InterlnalFrame.setClosable(true);
        CreateRooms_InterlnalFrame.setVisible(false);
        CreateRooms_InterlnalFrame.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Existing_Offers_label.setBackground(new java.awt.Color(81, 91, 212));
        Existing_Offers_label.setFont(new java.awt.Font("Microsoft YaHei", 1, 24)); // NOI18N
        Existing_Offers_label.setForeground(new java.awt.Color(245, 133, 41));
        Existing_Offers_label.setText("Existing Offers:");
        CreateRooms_InterlnalFrame.getContentPane().add(Existing_Offers_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, 200, 30));

        ExistingOffers_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(ExistingOffers_Table);

        CreateRooms_InterlnalFrame.getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 610, 450));

        External_Frame3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/White_Wallpaper.jpg"))); // NOI18N
        CreateRooms_InterlnalFrame.getContentPane().add(External_Frame3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 570));

        getContentPane().add(CreateRooms_InterlnalFrame, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 120, 650, 590));

        ChangeOffer_InternalFrame.setBackground(new java.awt.Color(255, 255, 255));
        ChangeOffer_InternalFrame.setBorder(null);
        ChangeOffer_InternalFrame.setClosable(true);
        ChangeOffer_InternalFrame.setVisible(false);
        ChangeOffer_InternalFrame.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ExpireDate_label1.setBackground(new java.awt.Color(81, 91, 212));
        ExpireDate_label1.setFont(new java.awt.Font("Microsoft YaHei", 1, 18)); // NOI18N
        ExpireDate_label1.setForeground(new java.awt.Color(245, 133, 41));
        ExpireDate_label1.setText("Expire Date:");
        ChangeOffer_InternalFrame.getContentPane().add(ExpireDate_label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 120, 30));

        Day_TextField1.setBackground(new java.awt.Color(255, 255, 255));
        Day_TextField1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Day_TextField1.setForeground(new java.awt.Color(32, 21, 14));
        Day_TextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Day_TextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(245, 133, 41)));
        Day_TextField1.setCaretColor(new java.awt.Color(0, 102, 204));
        Day_TextField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Day_TextField1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Day_TextField1MouseExited(evt);
            }
        });
        Day_TextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Day_TextField1ActionPerformed(evt);
            }
        });
        ChangeOffer_InternalFrame.getContentPane().add(Day_TextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 80, 20));

        SelectRoom_Label1.setBackground(new java.awt.Color(81, 91, 212));
        SelectRoom_Label1.setFont(new java.awt.Font("Microsoft YaHei", 1, 18)); // NOI18N
        SelectRoom_Label1.setForeground(new java.awt.Color(245, 133, 41));
        SelectRoom_Label1.setText("Select a Room:");
        ChangeOffer_InternalFrame.getContentPane().add(SelectRoom_Label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 140, 30));

        Discount_TextField1.setBackground(new java.awt.Color(255, 255, 255));
        Discount_TextField1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Discount_TextField1.setForeground(new java.awt.Color(32, 21, 14));
        Discount_TextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Discount_TextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(245, 133, 41)));
        Discount_TextField1.setCaretColor(new java.awt.Color(0, 102, 204));
        Discount_TextField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Discount_TextField1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Discount_TextField1MouseExited(evt);
            }
        });
        Discount_TextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Discount_TextField1ActionPerformed(evt);
            }
        });
        ChangeOffer_InternalFrame.getContentPane().add(Discount_TextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 130, 20));

        Year_TextField1.setBackground(new java.awt.Color(255, 255, 255));
        Year_TextField1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Year_TextField1.setForeground(new java.awt.Color(32, 21, 14));
        Year_TextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Year_TextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(245, 133, 41)));
        Year_TextField1.setCaretColor(new java.awt.Color(0, 102, 204));
        Year_TextField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Year_TextField1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Year_TextField1MouseExited(evt);
            }
        });
        Year_TextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Year_TextField1ActionPerformed(evt);
            }
        });
        ChangeOffer_InternalFrame.getContentPane().add(Year_TextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 80, 20));

        Month_TextField1.setBackground(new java.awt.Color(255, 255, 255));
        Month_TextField1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Month_TextField1.setForeground(new java.awt.Color(32, 21, 14));
        Month_TextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Month_TextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(245, 133, 41)));
        Month_TextField1.setCaretColor(new java.awt.Color(0, 102, 204));
        Month_TextField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Month_TextField1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Month_TextField1MouseExited(evt);
            }
        });
        Month_TextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Month_TextField1ActionPerformed(evt);
            }
        });
        ChangeOffer_InternalFrame.getContentPane().add(Month_TextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 80, 20));

        Name_TextField1.setBackground(new java.awt.Color(255, 255, 255));
        Name_TextField1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Name_TextField1.setForeground(new java.awt.Color(32, 21, 14));
        Name_TextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Name_TextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(245, 133, 41)));
        Name_TextField1.setCaretColor(new java.awt.Color(0, 102, 204));
        Name_TextField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Name_TextField1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Name_TextField1MouseExited(evt);
            }
        });
        Name_TextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Name_TextField1ActionPerformed(evt);
            }
        });
        ChangeOffer_InternalFrame.getContentPane().add(Name_TextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 340, 20));

        YearMonthDay_Label1.setBackground(new java.awt.Color(153, 153, 153));
        YearMonthDay_Label1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        YearMonthDay_Label1.setForeground(new java.awt.Color(245, 133, 41));
        YearMonthDay_Label1.setText("yyyy       -      mm        -     dd");
        ChangeOffer_InternalFrame.getContentPane().add(YearMonthDay_Label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 250, 30));

        SelectHotel_Label1.setBackground(new java.awt.Color(81, 91, 212));
        SelectHotel_Label1.setFont(new java.awt.Font("Microsoft YaHei", 1, 18)); // NOI18N
        SelectHotel_Label1.setForeground(new java.awt.Color(245, 133, 41));
        SelectHotel_Label1.setText("Select an Hotel:");
        ChangeOffer_InternalFrame.getContentPane().add(SelectHotel_Label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 140, 30));

        Name_Label1.setBackground(new java.awt.Color(81, 91, 212));
        Name_Label1.setFont(new java.awt.Font("Microsoft YaHei", 1, 18)); // NOI18N
        Name_Label1.setForeground(new java.awt.Color(245, 133, 41));
        Name_Label1.setText("Name:");
        ChangeOffer_InternalFrame.getContentPane().add(Name_Label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 90, 30));

        Discount_Label1.setBackground(new java.awt.Color(81, 91, 212));
        Discount_Label1.setFont(new java.awt.Font("Microsoft YaHei", 1, 18)); // NOI18N
        Discount_Label1.setForeground(new java.awt.Color(245, 133, 41));
        Discount_Label1.setText("Discount:");
        ChangeOffer_InternalFrame.getContentPane().add(Discount_Label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 140, 30));

        SelectRoom_ComboBox1.setBackground(new java.awt.Color(255, 255, 255));
        SelectRoom_ComboBox1.setForeground(new java.awt.Color(32, 21, 14));
        SelectRoom_ComboBox1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(245, 133, 41)));
        SelectRoom_ComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectRoom_ComboBox1ActionPerformed(evt);
            }
        });
        ChangeOffer_InternalFrame.getContentPane().add(SelectRoom_ComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 270, -1));

        SelectHotel_ComboBox1.setBackground(new java.awt.Color(255, 255, 255));
        SelectHotel_ComboBox1.setForeground(new java.awt.Color(51, 51, 51));
        SelectHotel_ComboBox1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(245, 133, 41)));
        SelectHotel_ComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectHotel_ComboBox1ActionPerformed(evt);
            }
        });
        ChangeOffer_InternalFrame.getContentPane().add(SelectHotel_ComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 270, -1));

        Offer_Creation_Button1.setFont(new java.awt.Font("Microsoft YaHei", 1, 18)); // NOI18N
        Offer_Creation_Button1.setForeground(new java.awt.Color(245, 133, 41));
        Offer_Creation_Button1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Change_icon (2).png"))); // NOI18N
        Offer_Creation_Button1.setText("Change Offer Info!");
        Offer_Creation_Button1.setBorderPainted(false);
        Offer_Creation_Button1.setContentAreaFilled(false);
        Offer_Creation_Button1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        Offer_Creation_Button1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Offer_Creation_Button1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ChangeOffer_InternalFrame.getContentPane().add(Offer_Creation_Button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 440, 210, 100));

        External_Frame2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/White_Wallpaper.jpg"))); // NOI18N
        ChangeOffer_InternalFrame.getContentPane().add(External_Frame2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 570));

        getContentPane().add(ChangeOffer_InternalFrame, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 120, 650, 590));

        DeleteOffer_InternalFrame.setBackground(new java.awt.Color(255, 255, 255));
        DeleteOffer_InternalFrame.setBorder(null);
        DeleteOffer_InternalFrame.setClosable(true);
        DeleteOffer_InternalFrame.setVisible(false);
        DeleteOffer_InternalFrame.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Existing_Offers_label1.setBackground(new java.awt.Color(81, 91, 212));
        Existing_Offers_label1.setFont(new java.awt.Font("Microsoft YaHei", 1, 24)); // NOI18N
        Existing_Offers_label1.setForeground(new java.awt.Color(236, 72, 76));
        Existing_Offers_label1.setText("Existing Offers:");
        DeleteOffer_InternalFrame.getContentPane().add(Existing_Offers_label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, 200, 30));

        ExistingOffers_Table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(ExistingOffers_Table1);

        DeleteOffer_InternalFrame.getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 610, 450));

        External_Frame4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/White_Wallpaper.jpg"))); // NOI18N
        DeleteOffer_InternalFrame.getContentPane().add(External_Frame4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 570));

        getContentPane().add(DeleteOffer_InternalFrame, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 120, 650, 590));

        Logo_Label.setFont(new java.awt.Font("Microsoft YaHei", 1, 36)); // NOI18N
        Logo_Label.setForeground(new java.awt.Color(129, 52, 175));
        Logo_Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Mini_Logo2.png"))); // NOI18N
        Logo_Label.setText("My Travel Home ");
        Logo_Label.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        getContentPane().add(Logo_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 10, 400, 70));

        Line_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/line.PNG"))); // NOI18N
        Line_label.setText("jLabel3");
        getContentPane().add(Line_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 80, 10, 630));

        Agency_Label.setBackground(new java.awt.Color(81, 91, 212));
        Agency_Label.setFont(new java.awt.Font("Microsoft YaHei", 1, 20)); // NOI18N
        Agency_Label.setForeground(new java.awt.Color(57, 23, 77));
        Agency_Label.setText("Hotel Management");
        getContentPane().add(Agency_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 80, 220, 30));

        Exit_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Exit Button.png"))); // NOI18N
        Exit_Button.setToolTipText("");
        Exit_Button.setBorder(null);
        Exit_Button.setContentAreaFilled(false);
        Exit_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Exit_ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(Exit_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 10, 30, 30));

        DeleteOffer_Button.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        DeleteOffer_Button.setForeground(new java.awt.Color(236, 72, 76));
        DeleteOffer_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Delete_icon (2).png"))); // NOI18N
        DeleteOffer_Button.setText("  Delete an Hotel");
        DeleteOffer_Button.setBorderPainted(false);
        DeleteOffer_Button.setContentAreaFilled(false);
        DeleteOffer_Button.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        DeleteOffer_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteOffer_ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(DeleteOffer_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 530, 230, 90));

        ChangeOffer_Button.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        ChangeOffer_Button.setForeground(new java.awt.Color(245, 133, 41));
        ChangeOffer_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Change_icon (2).png"))); // NOI18N
        ChangeOffer_Button.setText("  Change Hotel Info");
        ChangeOffer_Button.setBorderPainted(false);
        ChangeOffer_Button.setContentAreaFilled(false);
        ChangeOffer_Button.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        ChangeOffer_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChangeOffer_ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ChangeOffer_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 430, 240, 100));

        CreateHotel_Button.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        CreateHotel_Button.setForeground(new java.awt.Color(81, 91, 212));
        CreateHotel_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/hotel_icon_2.png"))); // NOI18N
        CreateHotel_Button.setText("  Create a New Hotel");
        CreateHotel_Button.setBorderPainted(false);
        CreateHotel_Button.setContentAreaFilled(false);
        CreateHotel_Button.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        CreateHotel_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateHotel_ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(CreateHotel_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 170, -1, -1));

        CreateHotel_Button1.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        CreateHotel_Button1.setForeground(new java.awt.Color(169, 146, 84));
        CreateHotel_Button1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Service_Icon.png"))); // NOI18N
        CreateHotel_Button1.setText("  Create a New Service");
        CreateHotel_Button1.setBorderPainted(false);
        CreateHotel_Button1.setContentAreaFilled(false);
        CreateHotel_Button1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        CreateHotel_Button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateHotel_Button1ActionPerformed(evt);
            }
        });
        getContentPane().add(CreateHotel_Button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 350, -1, -1));

        CreateHotel_Button2.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        CreateHotel_Button2.setForeground(new java.awt.Color(221, 42, 123));
        CreateHotel_Button2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Room_Icon.png"))); // NOI18N
        CreateHotel_Button2.setText("  Create a New Room");
        CreateHotel_Button2.setBorderPainted(false);
        CreateHotel_Button2.setContentAreaFilled(false);
        CreateHotel_Button2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        CreateHotel_Button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateHotel_Button2ActionPerformed(evt);
            }
        });
        getContentPane().add(CreateHotel_Button2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 260, -1, -1));

        Wallpaper_Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Snow_Hotel_Photo.jpg"))); // NOI18N
        Wallpaper_Label.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        getContentPane().add(Wallpaper_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 570, 700));

        External_Frame.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/White_Wallpaper.jpg"))); // NOI18N
        getContentPane().add(External_Frame, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Exit_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Exit_ButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_Exit_ButtonActionPerformed

    private void CreateHotel_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateHotel_ButtonActionPerformed

        CreateHotel_InternalFrame.setVisible(true);
        
    }//GEN-LAST:event_CreateHotel_ButtonActionPerformed

    private void SelectCountry_ComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectCountry_ComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SelectCountry_ComboBoxActionPerformed

    private void SelectHotelStars_ComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectHotelStars_ComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SelectHotelStars_ComboBoxActionPerformed

    private void Name_TextFieldMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Name_TextFieldMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_Name_TextFieldMouseEntered

    private void Name_TextFieldMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Name_TextFieldMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_Name_TextFieldMouseExited

    private void Name_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Name_TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Name_TextFieldActionPerformed

    private void Day_TextField1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Day_TextField1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_Day_TextField1MouseEntered

    private void Day_TextField1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Day_TextField1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_Day_TextField1MouseExited

    private void Day_TextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Day_TextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Day_TextField1ActionPerformed

    private void Discount_TextField1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Discount_TextField1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_Discount_TextField1MouseEntered

    private void Discount_TextField1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Discount_TextField1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_Discount_TextField1MouseExited

    private void Discount_TextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Discount_TextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Discount_TextField1ActionPerformed

    private void Year_TextField1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Year_TextField1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_Year_TextField1MouseEntered

    private void Year_TextField1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Year_TextField1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_Year_TextField1MouseExited

    private void Year_TextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Year_TextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Year_TextField1ActionPerformed

    private void Month_TextField1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Month_TextField1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_Month_TextField1MouseEntered

    private void Month_TextField1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Month_TextField1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_Month_TextField1MouseExited

    private void Month_TextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Month_TextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Month_TextField1ActionPerformed

    private void Name_TextField1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Name_TextField1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_Name_TextField1MouseEntered

    private void Name_TextField1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Name_TextField1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_Name_TextField1MouseExited

    private void Name_TextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Name_TextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Name_TextField1ActionPerformed

    private void SelectRoom_ComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectRoom_ComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SelectRoom_ComboBox1ActionPerformed

    private void SelectHotel_ComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectHotel_ComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SelectHotel_ComboBox1ActionPerformed

    private void ChangeOffer_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChangeOffer_ButtonActionPerformed
        CreateRooms_InterlnalFrame.setVisible(true);
    }//GEN-LAST:event_ChangeOffer_ButtonActionPerformed

    private void DeleteOffer_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteOffer_ButtonActionPerformed
        DeleteOffer_InternalFrame.setVisible(true);
    }//GEN-LAST:event_DeleteOffer_ButtonActionPerformed

    private void CreateHotel_Button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateHotel_Button1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CreateHotel_Button1ActionPerformed

    private void CreateHotel_Button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateHotel_Button2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CreateHotel_Button2ActionPerformed

    private void SelectHotelCategory_ComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectHotelCategory_ComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SelectHotelCategory_ComboBoxActionPerformed

    private void SelectProvince_ComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectProvince_ComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SelectProvince_ComboBoxActionPerformed

    private void SelectCatnton_ComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectCatnton_ComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SelectCatnton_ComboBoxActionPerformed

    private void Photo_ButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Photo_ButtonMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_Photo_ButtonMouseEntered

    private void Photo_ButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Photo_ButtonMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_Photo_ButtonMouseExited

    private void Photo_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Photo_ButtonActionPerformed

    }//GEN-LAST:event_Photo_ButtonActionPerformed

    private void SelectDistrict_ComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectDistrict_ComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SelectDistrict_ComboBoxActionPerformed

    /**
     * @param args the command line arguments
    */

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Hotel_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Hotel_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Hotel_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Hotel_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Hotel_Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Agency_Label;
    private javax.swing.JButton ChangeOffer_Button;
    private javax.swing.JInternalFrame ChangeOffer_InternalFrame;
    private javax.swing.JButton CreateHotel_Button;
    private javax.swing.JButton CreateHotel_Button1;
    private javax.swing.JButton CreateHotel_Button2;
    private javax.swing.JInternalFrame CreateHotel_InternalFrame;
    private javax.swing.JInternalFrame CreateRooms_InterlnalFrame;
    private javax.swing.JTextField Day_TextField1;
    private javax.swing.JButton DeleteOffer_Button;
    private javax.swing.JInternalFrame DeleteOffer_InternalFrame;
    private javax.swing.JLabel Discount_Label1;
    private javax.swing.JTextField Discount_TextField1;
    private javax.swing.JTable ExistingOffers_Table;
    private javax.swing.JTable ExistingOffers_Table1;
    private javax.swing.JLabel Existing_Offers_label;
    private javax.swing.JLabel Existing_Offers_label1;
    private javax.swing.JButton Exit_Button;
    private javax.swing.JLabel ExpireDate_label1;
    private javax.swing.JLabel External_Frame;
    private javax.swing.JLabel External_Frame1;
    private javax.swing.JLabel External_Frame2;
    private javax.swing.JLabel External_Frame3;
    private javax.swing.JLabel External_Frame4;
    private javax.swing.JLabel Line_label;
    private javax.swing.JLabel Logo_Label;
    private javax.swing.JTextField Month_TextField1;
    private javax.swing.JLabel Name_Label;
    private javax.swing.JLabel Name_Label1;
    private javax.swing.JTextField Name_TextField;
    private javax.swing.JTextField Name_TextField1;
    private javax.swing.JButton Offer_Creation_Button;
    private javax.swing.JButton Offer_Creation_Button1;
    private javax.swing.JButton Photo_Button;
    private javax.swing.JLabel Photo_Label;
    private javax.swing.JLabel SelectCanton_Label;
    private javax.swing.JComboBox<String> SelectCatnton_ComboBox;
    private javax.swing.JComboBox<String> SelectCountry_ComboBox;
    private javax.swing.JLabel SelectCountry_Label;
    private javax.swing.JComboBox<String> SelectDistrict_ComboBox;
    private javax.swing.JLabel SelectDistrict_Label;
    private javax.swing.JComboBox<String> SelectHotelCategory_ComboBox;
    private javax.swing.JLabel SelectHotelCategory_Label;
    private javax.swing.JComboBox<String> SelectHotelStars_ComboBox;
    private javax.swing.JLabel SelectHotelStars_Label;
    private javax.swing.JComboBox<String> SelectHotel_ComboBox1;
    private javax.swing.JLabel SelectHotel_Label1;
    private javax.swing.JLabel SelectLocation_Label;
    private javax.swing.JComboBox<String> SelectProvince_ComboBox;
    private javax.swing.JLabel SelectProvince_Label;
    private javax.swing.JComboBox<String> SelectRoom_ComboBox1;
    private javax.swing.JLabel SelectRoom_Label1;
    private javax.swing.JLabel Wallpaper_Label;
    private javax.swing.JLabel YearMonthDay_Label1;
    private javax.swing.JTextField Year_TextField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
