/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UIFrames;

/**
 *
 * @author rony1
 */
public class Login_Menu extends javax.swing.JFrame {

    /**
     * Creates new form Login_Window
     */
    public Login_Menu() {
        
        this.setUndecorated(true);
        this.setResizable(false);
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Exit_Button = new javax.swing.JButton();
        Logo = new javax.swing.JLabel();
        Line_label = new javax.swing.JLabel();
        Log_In_Label = new javax.swing.JLabel();
        Register_Label = new javax.swing.JLabel();
        line = new javax.swing.JLabel();
        Log_In_Button = new javax.swing.JButton();
        Create_User_Button = new javax.swing.JButton();
        Crete_Agency_Button = new javax.swing.JButton();
        Create_Hotel_Button = new javax.swing.JButton();
        Menu = new javax.swing.JLabel();
        Wallpaper1 = new javax.swing.JLabel();
        External_Frame = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Exit_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Exit Button.png"))); // NOI18N
        Exit_Button.setToolTipText("");
        Exit_Button.setBorder(null);
        Exit_Button.setContentAreaFilled(false);
        Exit_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Exit_ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(Exit_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 10, 30, 30));

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Main_Logo.png"))); // NOI18N
        getContentPane().add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, -10, 760, 260));

        Line_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Menu.jpg"))); // NOI18N
        getContentPane().add(Line_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, 1050, 10));

        Log_In_Label.setFont(new java.awt.Font("Microsoft YaHei", 1, 18)); // NOI18N
        Log_In_Label.setForeground(new java.awt.Color(0, 0, 0));
        Log_In_Label.setText("Log In");
        getContentPane().add(Log_In_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 330, 70, -1));

        Register_Label.setFont(new java.awt.Font("Microsoft YaHei", 1, 18)); // NOI18N
        Register_Label.setForeground(new java.awt.Color(0, 0, 0));
        Register_Label.setText("Or Register...");
        getContentPane().add(Register_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 330, 130, 20));

        line.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/line.PNG"))); // NOI18N
        line.setText("jLabel3");
        getContentPane().add(line, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 390, 10, 230));

        Log_In_Button.setFont(new java.awt.Font("Microsoft YaHei", 1, 18)); // NOI18N
        Log_In_Button.setForeground(new java.awt.Color(0, 0, 0));
        Log_In_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Log_In_Button.png"))); // NOI18N
        Log_In_Button.setBorderPainted(false);
        Log_In_Button.setContentAreaFilled(false);
        Log_In_Button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Log_In_Button.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Log_In_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Log_In_ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(Log_In_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 380, 260, 260));

        Create_User_Button.setBackground(new java.awt.Color(0, 0, 0));
        Create_User_Button.setFont(new java.awt.Font("Microsoft YaHei", 1, 18)); // NOI18N
        Create_User_Button.setForeground(new java.awt.Color(0, 0, 0));
        Create_User_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/User.png"))); // NOI18N
        Create_User_Button.setText("  Create a New User");
        Create_User_Button.setBorderPainted(false);
        Create_User_Button.setContentAreaFilled(false);
        Create_User_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Create_User_ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(Create_User_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 390, 300, 70));

        Crete_Agency_Button.setFont(new java.awt.Font("Microsoft YaHei", 1, 18)); // NOI18N
        Crete_Agency_Button.setForeground(new java.awt.Color(0, 0, 0));
        Crete_Agency_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Travel Agent.png"))); // NOI18N
        Crete_Agency_Button.setText("  Create a New Agency");
        Crete_Agency_Button.setBorderPainted(false);
        Crete_Agency_Button.setContentAreaFilled(false);
        Crete_Agency_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Crete_Agency_ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(Crete_Agency_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 480, 310, 70));

        Create_Hotel_Button.setFont(new java.awt.Font("Microsoft YaHei", 1, 18)); // NOI18N
        Create_Hotel_Button.setForeground(new java.awt.Color(0, 0, 0));
        Create_Hotel_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Hotel.png"))); // NOI18N
        Create_Hotel_Button.setText("  Create a New Hotel");
        Create_Hotel_Button.setBorderPainted(false);
        Create_Hotel_Button.setContentAreaFilled(false);
        Create_Hotel_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Create_Hotel_ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(Create_Hotel_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(723, 570, 290, 70));

        Menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Transparency_Wallpaper.png"))); // NOI18N
        getContentPane().add(Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, 870, 390));

        Wallpaper1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/GifWallpaper.gif"))); // NOI18N
        getContentPane().add(Wallpaper1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1260, 700));

        External_Frame.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/White_Wallpaper.jpg"))); // NOI18N
        External_Frame.setText("jLabel1");
        getContentPane().add(External_Frame, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Exit_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Exit_ButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_Exit_ButtonActionPerformed

    private void Create_User_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Create_User_ButtonActionPerformed
        Register_User_Window result = new Register_User_Window();
        result.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_Create_User_ButtonActionPerformed

    private void Crete_Agency_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Crete_Agency_ButtonActionPerformed
        Register_Agency_Window result = new Register_Agency_Window();
        result.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_Crete_Agency_ButtonActionPerformed

    private void Create_Hotel_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Create_Hotel_ButtonActionPerformed
       Register_Hotel_Admin_Window result = new Register_Hotel_Admin_Window();
       result.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_Create_Hotel_ButtonActionPerformed

    private void Log_In_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Log_In_ButtonActionPerformed
       Login_Window result = new Login_Window();
       result.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_Log_In_ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login_Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Create_Hotel_Button;
    private javax.swing.JButton Create_User_Button;
    private javax.swing.JButton Crete_Agency_Button;
    private javax.swing.JButton Exit_Button;
    private javax.swing.JLabel External_Frame;
    private javax.swing.JLabel Line_label;
    private javax.swing.JButton Log_In_Button;
    private javax.swing.JLabel Log_In_Label;
    private javax.swing.JLabel Logo;
    private javax.swing.JLabel Menu;
    private javax.swing.JLabel Register_Label;
    private javax.swing.JLabel Wallpaper1;
    private javax.swing.JLabel line;
    // End of variables declaration//GEN-END:variables
}
