/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UIFrames;

/**
 *
 * @author rony1
 */
public class Register_User_Window extends javax.swing.JFrame {

    /**
     * Creates new form Login_Window
     */
    public Register_User_Window() {
        this.setUndecorated(true);
        this.setResizable(false);
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Exit_Button = new javax.swing.JButton();
        Gender_Label = new javax.swing.JLabel();
        FirstName_Label = new javax.swing.JLabel();
        LastName_Label = new javax.swing.JLabel();
        BirthDay_Label = new javax.swing.JLabel();
        Password_Label = new javax.swing.JLabel();
        Nationality_Label = new javax.swing.JLabel();
        NewUser_Label = new javax.swing.JLabel();
        Bank_Account = new javax.swing.JLabel();
        FirstName_Label1 = new javax.swing.JLabel();
        Uername_Label1 = new javax.swing.JLabel();
        Photo_Label = new javax.swing.JLabel();
        Password_TextField = new javax.swing.JTextField();
        FirstName_TextField = new javax.swing.JTextField();
        Lastname_TextField = new javax.swing.JTextField();
        BirthDay_Year_ComboBox = new javax.swing.JComboBox<>();
        BirthDay_Month_ComboBox = new javax.swing.JComboBox<>();
        BirthDay_Day_ComboBox = new javax.swing.JComboBox<>();
        Gender_ComboBox = new javax.swing.JComboBox<>();
        Nationality_ComboBox = new javax.swing.JComboBox<>();
        Username_Textfield = new javax.swing.JTextField();
        Identification_textField = new javax.swing.JTextField();
        Register_Button = new javax.swing.JButton();
        Bank_Account_TextField = new javax.swing.JTextField();
        Photo_Button = new javax.swing.JButton();
        RegisterText = new javax.swing.JLabel();
        HorizontalText = new javax.swing.JLabel();
        Hotel_Photo = new javax.swing.JLabel();
        External_Frame = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Exit_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Exit Button.png"))); // NOI18N
        Exit_Button.setToolTipText("");
        Exit_Button.setBorder(null);
        Exit_Button.setContentAreaFilled(false);
        Exit_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Exit_ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(Exit_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 10, 30, 30));

        Gender_Label.setBackground(new java.awt.Color(255, 255, 255));
        Gender_Label.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Gender_Label.setForeground(new java.awt.Color(129, 52, 175));
        Gender_Label.setText("Gender:");
        getContentPane().add(Gender_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 460, 120, 30));

        FirstName_Label.setBackground(new java.awt.Color(255, 255, 255));
        FirstName_Label.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        FirstName_Label.setForeground(new java.awt.Color(129, 52, 175));
        FirstName_Label.setText("Identification:");
        getContentPane().add(FirstName_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 140, 120, 30));

        LastName_Label.setBackground(new java.awt.Color(255, 255, 255));
        LastName_Label.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        LastName_Label.setForeground(new java.awt.Color(129, 52, 175));
        LastName_Label.setText("Last Name:");
        getContentPane().add(LastName_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 250, 120, 30));

        BirthDay_Label.setBackground(new java.awt.Color(255, 255, 255));
        BirthDay_Label.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        BirthDay_Label.setForeground(new java.awt.Color(129, 52, 175));
        BirthDay_Label.setText("Birth Day:");
        getContentPane().add(BirthDay_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 310, 120, 30));

        Password_Label.setBackground(new java.awt.Color(255, 255, 255));
        Password_Label.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Password_Label.setForeground(new java.awt.Color(129, 52, 175));
        Password_Label.setText("Password:");
        getContentPane().add(Password_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 590, 120, 30));

        Nationality_Label.setBackground(new java.awt.Color(255, 255, 255));
        Nationality_Label.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Nationality_Label.setForeground(new java.awt.Color(129, 52, 175));
        Nationality_Label.setText("Nationality:");
        getContentPane().add(Nationality_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 400, 120, 30));

        NewUser_Label.setBackground(new java.awt.Color(153, 153, 153));
        NewUser_Label.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        NewUser_Label.setForeground(new java.awt.Color(129, 52, 175));
        NewUser_Label.setText("yyyy       -      mm        -     dd");
        getContentPane().add(NewUser_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 370, 250, 30));

        Bank_Account.setBackground(new java.awt.Color(255, 255, 255));
        Bank_Account.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Bank_Account.setForeground(new java.awt.Color(129, 52, 175));
        Bank_Account.setText("Bank Account:");
        getContentPane().add(Bank_Account, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 650, 140, 30));

        FirstName_Label1.setBackground(new java.awt.Color(255, 255, 255));
        FirstName_Label1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        FirstName_Label1.setForeground(new java.awt.Color(129, 52, 175));
        FirstName_Label1.setText("First Name:");
        getContentPane().add(FirstName_Label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 200, 120, 30));

        Uername_Label1.setBackground(new java.awt.Color(255, 255, 255));
        Uername_Label1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Uername_Label1.setForeground(new java.awt.Color(129, 52, 175));
        Uername_Label1.setText("Username:");
        getContentPane().add(Uername_Label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 530, 120, 30));

        Photo_Label.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Photo_Label.setForeground(new java.awt.Color(129, 52, 175));
        Photo_Label.setText(" Add a Photo");
        getContentPane().add(Photo_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 640, 120, 30));

        Password_TextField.setBackground(new java.awt.Color(255, 255, 255));
        Password_TextField.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Password_TextField.setForeground(new java.awt.Color(32, 21, 14));
        Password_TextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Password_TextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(129, 52, 175), 2));
        Password_TextField.setCaretColor(new java.awt.Color(44, 168, 109));
        Password_TextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Password_TextFieldMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Password_TextFieldMouseExited(evt);
            }
        });
        Password_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Password_TextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(Password_TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 630, 360, 20));

        FirstName_TextField.setBackground(new java.awt.Color(255, 255, 255));
        FirstName_TextField.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        FirstName_TextField.setForeground(new java.awt.Color(32, 21, 14));
        FirstName_TextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        FirstName_TextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(129, 52, 175), 2));
        FirstName_TextField.setCaretColor(new java.awt.Color(44, 168, 109));
        FirstName_TextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                FirstName_TextFieldMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                FirstName_TextFieldMouseExited(evt);
            }
        });
        FirstName_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FirstName_TextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(FirstName_TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 230, 360, 20));

        Lastname_TextField.setBackground(new java.awt.Color(255, 255, 255));
        Lastname_TextField.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Lastname_TextField.setForeground(new java.awt.Color(32, 21, 14));
        Lastname_TextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Lastname_TextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(129, 52, 175), 2));
        Lastname_TextField.setCaretColor(new java.awt.Color(44, 168, 109));
        Lastname_TextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Lastname_TextFieldMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Lastname_TextFieldMouseExited(evt);
            }
        });
        Lastname_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Lastname_TextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(Lastname_TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 280, 360, 20));

        BirthDay_Year_ComboBox.setBackground(new java.awt.Color(255, 255, 255));
        BirthDay_Year_ComboBox.setForeground(new java.awt.Color(32, 21, 14));
        BirthDay_Year_ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        BirthDay_Year_ComboBox.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(129, 52, 175)));
        BirthDay_Year_ComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BirthDay_Year_ComboBoxActionPerformed(evt);
            }
        });
        getContentPane().add(BirthDay_Year_ComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 340, 80, -1));

        BirthDay_Month_ComboBox.setBackground(new java.awt.Color(255, 255, 255));
        BirthDay_Month_ComboBox.setForeground(new java.awt.Color(32, 21, 14));
        BirthDay_Month_ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        BirthDay_Month_ComboBox.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(129, 52, 175)));
        BirthDay_Month_ComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BirthDay_Month_ComboBoxActionPerformed(evt);
            }
        });
        getContentPane().add(BirthDay_Month_ComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 340, 80, -1));

        BirthDay_Day_ComboBox.setBackground(new java.awt.Color(255, 255, 255));
        BirthDay_Day_ComboBox.setForeground(new java.awt.Color(32, 21, 14));
        BirthDay_Day_ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        BirthDay_Day_ComboBox.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(129, 52, 175)));
        BirthDay_Day_ComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BirthDay_Day_ComboBoxActionPerformed(evt);
            }
        });
        getContentPane().add(BirthDay_Day_ComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 340, 80, -1));

        Gender_ComboBox.setBackground(new java.awt.Color(255, 255, 255));
        Gender_ComboBox.setForeground(new java.awt.Color(32, 21, 14));
        Gender_ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Other" }));
        Gender_ComboBox.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(129, 52, 175)));
        Gender_ComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Gender_ComboBoxActionPerformed(evt);
            }
        });
        getContentPane().add(Gender_ComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 490, 260, -1));

        Nationality_ComboBox.setBackground(new java.awt.Color(255, 255, 255));
        Nationality_ComboBox.setForeground(new java.awt.Color(32, 21, 14));
        Nationality_ComboBox.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(129, 52, 175)));
        Nationality_ComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nationality_ComboBoxActionPerformed(evt);
            }
        });
        getContentPane().add(Nationality_ComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 430, 260, -1));

        Username_Textfield.setBackground(new java.awt.Color(255, 255, 255));
        Username_Textfield.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Username_Textfield.setForeground(new java.awt.Color(32, 21, 14));
        Username_Textfield.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Username_Textfield.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(129, 52, 175), 2));
        Username_Textfield.setCaretColor(new java.awt.Color(44, 168, 109));
        Username_Textfield.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Username_TextfieldMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Username_TextfieldMouseExited(evt);
            }
        });
        Username_Textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Username_TextfieldActionPerformed(evt);
            }
        });
        getContentPane().add(Username_Textfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 560, 360, 20));

        Identification_textField.setBackground(new java.awt.Color(255, 255, 255));
        Identification_textField.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Identification_textField.setForeground(new java.awt.Color(32, 21, 14));
        Identification_textField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Identification_textField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(129, 52, 175), 2));
        Identification_textField.setCaretColor(new java.awt.Color(44, 168, 109));
        Identification_textField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Identification_textFieldMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Identification_textFieldMouseExited(evt);
            }
        });
        Identification_textField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Identification_textFieldActionPerformed(evt);
            }
        });
        getContentPane().add(Identification_textField, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 170, 360, 20));

        Register_Button.setBackground(new java.awt.Color(129, 52, 175));
        Register_Button.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        Register_Button.setForeground(new java.awt.Color(255, 255, 255));
        Register_Button.setText("Register Now!");
        Register_Button.setBorder(null);
        Register_Button.setBorderPainted(false);
        Register_Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Register_ButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Register_ButtonMouseExited(evt);
            }
        });
        Register_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Register_ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(Register_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 330, 160, 150));

        Bank_Account_TextField.setBackground(new java.awt.Color(255, 255, 255));
        Bank_Account_TextField.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Bank_Account_TextField.setForeground(new java.awt.Color(32, 21, 14));
        Bank_Account_TextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Bank_Account_TextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(129, 52, 175), 2));
        Bank_Account_TextField.setCaretColor(new java.awt.Color(44, 168, 109));
        Bank_Account_TextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Bank_Account_TextFieldMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Bank_Account_TextFieldMouseExited(evt);
            }
        });
        Bank_Account_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bank_Account_TextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(Bank_Account_TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 680, 360, 20));

        Photo_Button.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        Photo_Button.setForeground(new java.awt.Color(153, 153, 153));
        Photo_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/photo.png"))); // NOI18N
        Photo_Button.setBorderPainted(false);
        Photo_Button.setContentAreaFilled(false);
        Photo_Button.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        Photo_Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Photo_ButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Photo_ButtonMouseExited(evt);
            }
        });
        Photo_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Photo_ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(Photo_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 540, 110, 100));

        RegisterText.setFont(new java.awt.Font("Microsoft YaHei", 1, 36)); // NOI18N
        RegisterText.setForeground(new java.awt.Color(129, 52, 175));
        RegisterText.setText("Register a New User");
        getContentPane().add(RegisterText, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 30, 520, 70));

        HorizontalText.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/line_horizontal.PNG"))); // NOI18N
        getContentPane().add(HorizontalText, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 110, 580, 10));

        Hotel_Photo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Hotel_Users.jpg"))); // NOI18N
        getContentPane().add(Hotel_Photo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 620, 700));

        External_Frame.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/White_Wallpaper.jpg"))); // NOI18N
        External_Frame.setText("jLabel1");
        getContentPane().add(External_Frame, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Exit_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Exit_ButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_Exit_ButtonActionPerformed

    private void Password_TextFieldMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Password_TextFieldMouseEntered
        Password_TextField.setBackground(new java.awt.Color(216,216,216));
    }//GEN-LAST:event_Password_TextFieldMouseEntered

    private void Password_TextFieldMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Password_TextFieldMouseExited
        Password_TextField.setBackground(new java.awt.Color(255,255,255));
    }//GEN-LAST:event_Password_TextFieldMouseExited

    private void Password_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Password_TextFieldActionPerformed

    }//GEN-LAST:event_Password_TextFieldActionPerformed

    private void FirstName_TextFieldMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FirstName_TextFieldMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_FirstName_TextFieldMouseEntered

    private void FirstName_TextFieldMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FirstName_TextFieldMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_FirstName_TextFieldMouseExited

    private void FirstName_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FirstName_TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FirstName_TextFieldActionPerformed

    private void Lastname_TextFieldMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lastname_TextFieldMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_Lastname_TextFieldMouseEntered

    private void Lastname_TextFieldMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lastname_TextFieldMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_Lastname_TextFieldMouseExited

    private void Lastname_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Lastname_TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Lastname_TextFieldActionPerformed

    private void Gender_ComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Gender_ComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Gender_ComboBoxActionPerformed

    private void Nationality_ComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nationality_ComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Nationality_ComboBoxActionPerformed

    private void Username_TextfieldMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Username_TextfieldMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_Username_TextfieldMouseEntered

    private void Username_TextfieldMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Username_TextfieldMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_Username_TextfieldMouseExited

    private void Username_TextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Username_TextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Username_TextfieldActionPerformed

    private void Register_ButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Register_ButtonMouseEntered
        Register_Button.setBackground(new java.awt.Color(57,23,77));
    }//GEN-LAST:event_Register_ButtonMouseEntered

    private void Register_ButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Register_ButtonMouseExited
       Register_Button.setBackground(new java.awt.Color(129,52,175));
    }//GEN-LAST:event_Register_ButtonMouseExited

    private void Register_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Register_ButtonActionPerformed
       // User_Main_Menu result = new User_Main_Menu();
       // result.setVisible(true);
        //this.setVisible(false);
    }//GEN-LAST:event_Register_ButtonActionPerformed

    private void BirthDay_Day_ComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BirthDay_Day_ComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BirthDay_Day_ComboBoxActionPerformed

    private void BirthDay_Month_ComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BirthDay_Month_ComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BirthDay_Month_ComboBoxActionPerformed

    private void BirthDay_Year_ComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BirthDay_Year_ComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BirthDay_Year_ComboBoxActionPerformed

    private void Identification_textFieldMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Identification_textFieldMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_Identification_textFieldMouseEntered

    private void Identification_textFieldMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Identification_textFieldMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_Identification_textFieldMouseExited

    private void Identification_textFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Identification_textFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Identification_textFieldActionPerformed

    private void Bank_Account_TextFieldMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Bank_Account_TextFieldMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_Bank_Account_TextFieldMouseEntered

    private void Bank_Account_TextFieldMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Bank_Account_TextFieldMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_Bank_Account_TextFieldMouseExited

    private void Bank_Account_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bank_Account_TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Bank_Account_TextFieldActionPerformed

    private void Photo_ButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Photo_ButtonMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_Photo_ButtonMouseEntered

    private void Photo_ButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Photo_ButtonMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_Photo_ButtonMouseExited

    private void Photo_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Photo_ButtonActionPerformed

    }//GEN-LAST:event_Photo_ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register_User_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register_User_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register_User_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register_User_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register_User_Window().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Bank_Account;
    private javax.swing.JTextField Bank_Account_TextField;
    private javax.swing.JComboBox<String> BirthDay_Day_ComboBox;
    private javax.swing.JLabel BirthDay_Label;
    private javax.swing.JComboBox<String> BirthDay_Month_ComboBox;
    private javax.swing.JComboBox<String> BirthDay_Year_ComboBox;
    private javax.swing.JButton Exit_Button;
    private javax.swing.JLabel External_Frame;
    private javax.swing.JLabel FirstName_Label;
    private javax.swing.JLabel FirstName_Label1;
    private javax.swing.JTextField FirstName_TextField;
    private javax.swing.JComboBox<String> Gender_ComboBox;
    private javax.swing.JLabel Gender_Label;
    private javax.swing.JLabel HorizontalText;
    private javax.swing.JLabel Hotel_Photo;
    private javax.swing.JTextField Identification_textField;
    private javax.swing.JLabel LastName_Label;
    private javax.swing.JTextField Lastname_TextField;
    private javax.swing.JComboBox<String> Nationality_ComboBox;
    private javax.swing.JLabel Nationality_Label;
    private javax.swing.JLabel NewUser_Label;
    private javax.swing.JLabel Password_Label;
    private javax.swing.JTextField Password_TextField;
    private javax.swing.JButton Photo_Button;
    private javax.swing.JLabel Photo_Label;
    private javax.swing.JLabel RegisterText;
    private javax.swing.JButton Register_Button;
    private javax.swing.JLabel Uername_Label1;
    private javax.swing.JTextField Username_Textfield;
    // End of variables declaration//GEN-END:variables
}
