/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UIFrames;

/**
 *
 * @author rony1
 */
public class Register_Agency_Window extends javax.swing.JFrame {

    /**
     * Creates new form Login_Window
     */
    public Register_Agency_Window() {
        this.setUndecorated(true);
        this.setResizable(false);
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Exit_Button = new javax.swing.JButton();
        AgencyName_Label = new javax.swing.JLabel();
        Password_Label = new javax.swing.JLabel();
        Password_TextField = new javax.swing.JTextField();
        AgencyName_TextField = new javax.swing.JTextField();
        Photo_Button = new javax.swing.JButton();
        Register_Button = new javax.swing.JButton();
        Photo_Label = new javax.swing.JLabel();
        RegisterText = new javax.swing.JLabel();
        HorizontalText = new javax.swing.JLabel();
        Hotel_Photo = new javax.swing.JLabel();
        External_Frame = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Exit_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Exit Button.png"))); // NOI18N
        Exit_Button.setToolTipText("");
        Exit_Button.setBorder(null);
        Exit_Button.setContentAreaFilled(false);
        Exit_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Exit_ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(Exit_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 10, 30, 30));

        AgencyName_Label.setBackground(new java.awt.Color(255, 255, 255));
        AgencyName_Label.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        AgencyName_Label.setForeground(new java.awt.Color(129, 52, 175));
        AgencyName_Label.setText("Agency Name:");
        getContentPane().add(AgencyName_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 270, 140, 30));

        Password_Label.setBackground(new java.awt.Color(255, 255, 255));
        Password_Label.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Password_Label.setForeground(new java.awt.Color(129, 52, 175));
        Password_Label.setText("Password:");
        getContentPane().add(Password_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 340, 120, 30));

        Password_TextField.setBackground(new java.awt.Color(255, 255, 255));
        Password_TextField.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Password_TextField.setForeground(new java.awt.Color(32, 21, 14));
        Password_TextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Password_TextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(129, 52, 175), 2));
        Password_TextField.setCaretColor(new java.awt.Color(44, 168, 109));
        Password_TextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Password_TextFieldMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Password_TextFieldMouseExited(evt);
            }
        });
        Password_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Password_TextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(Password_TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 380, 360, 20));

        AgencyName_TextField.setBackground(new java.awt.Color(255, 255, 255));
        AgencyName_TextField.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        AgencyName_TextField.setForeground(new java.awt.Color(32, 21, 14));
        AgencyName_TextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        AgencyName_TextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(129, 52, 175), 2));
        AgencyName_TextField.setCaretColor(new java.awt.Color(44, 168, 109));
        AgencyName_TextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AgencyName_TextFieldMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AgencyName_TextFieldMouseExited(evt);
            }
        });
        AgencyName_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgencyName_TextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(AgencyName_TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 310, 360, 20));

        Photo_Button.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        Photo_Button.setForeground(new java.awt.Color(153, 153, 153));
        Photo_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/photo.png"))); // NOI18N
        Photo_Button.setBorderPainted(false);
        Photo_Button.setContentAreaFilled(false);
        Photo_Button.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        Photo_Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Photo_ButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Photo_ButtonMouseExited(evt);
            }
        });
        Photo_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Photo_ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(Photo_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 430, 110, 100));

        Register_Button.setBackground(new java.awt.Color(129, 52, 175));
        Register_Button.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        Register_Button.setForeground(new java.awt.Color(255, 255, 255));
        Register_Button.setText("Register Now!");
        Register_Button.setBorder(null);
        Register_Button.setBorderPainted(false);
        Register_Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Register_ButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Register_ButtonMouseExited(evt);
            }
        });
        Register_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Register_ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(Register_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 330, 160, 150));

        Photo_Label.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Photo_Label.setForeground(new java.awt.Color(129, 52, 175));
        Photo_Label.setText(" Add a Photo");
        getContentPane().add(Photo_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 520, 120, 30));

        RegisterText.setFont(new java.awt.Font("Microsoft YaHei", 1, 36)); // NOI18N
        RegisterText.setForeground(new java.awt.Color(129, 52, 175));
        RegisterText.setText("Register a New Agency");
        getContentPane().add(RegisterText, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 30, 430, 70));

        HorizontalText.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/line_horizontal.PNG"))); // NOI18N
        getContentPane().add(HorizontalText, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 110, 580, 10));

        Hotel_Photo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Agency.jpg"))); // NOI18N
        getContentPane().add(Hotel_Photo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 620, 700));

        External_Frame.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/White_Wallpaper.jpg"))); // NOI18N
        External_Frame.setText("jLabel1");
        getContentPane().add(External_Frame, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Exit_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Exit_ButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_Exit_ButtonActionPerformed

    private void Password_TextFieldMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Password_TextFieldMouseEntered
        Password_TextField.setBackground(new java.awt.Color(216,216,216));
    }//GEN-LAST:event_Password_TextFieldMouseEntered

    private void Password_TextFieldMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Password_TextFieldMouseExited
        Password_TextField.setBackground(new java.awt.Color(255,255,255));
    }//GEN-LAST:event_Password_TextFieldMouseExited

    private void Password_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Password_TextFieldActionPerformed

    }//GEN-LAST:event_Password_TextFieldActionPerformed

    private void AgencyName_TextFieldMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AgencyName_TextFieldMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_AgencyName_TextFieldMouseEntered

    private void AgencyName_TextFieldMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AgencyName_TextFieldMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_AgencyName_TextFieldMouseExited

    private void AgencyName_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgencyName_TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AgencyName_TextFieldActionPerformed

    private void Register_ButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Register_ButtonMouseEntered
        Register_Button.setBackground(new java.awt.Color(57,23,77));
    }//GEN-LAST:event_Register_ButtonMouseEntered

    private void Register_ButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Register_ButtonMouseExited
       Register_Button.setBackground(new java.awt.Color(129,52,175));
    }//GEN-LAST:event_Register_ButtonMouseExited

    private void Register_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Register_ButtonActionPerformed
       // User_Main_Menu result = new User_Main_Menu();
       // result.setVisible(true);
        //this.setVisible(false);
    }//GEN-LAST:event_Register_ButtonActionPerformed

    private void Photo_ButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Photo_ButtonMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_Photo_ButtonMouseEntered

    private void Photo_ButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Photo_ButtonMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_Photo_ButtonMouseExited

    private void Photo_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Photo_ButtonActionPerformed

    }//GEN-LAST:event_Photo_ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register_Agency_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register_Agency_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register_Agency_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register_Agency_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register_Agency_Window().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AgencyName_Label;
    private javax.swing.JTextField AgencyName_TextField;
    private javax.swing.JButton Exit_Button;
    private javax.swing.JLabel External_Frame;
    private javax.swing.JLabel HorizontalText;
    private javax.swing.JLabel Hotel_Photo;
    private javax.swing.JLabel Password_Label;
    private javax.swing.JTextField Password_TextField;
    private javax.swing.JButton Photo_Button;
    private javax.swing.JLabel Photo_Label;
    private javax.swing.JLabel RegisterText;
    private javax.swing.JButton Register_Button;
    // End of variables declaration//GEN-END:variables
}
